Neal2
EasyChef2022/back-end pull request #8
Opened 2022-03-13 18:52 UTC by CardinalNeal

update new function in user.view.py for change password

2022-03-13 19:01 UTC, JunxiHe459 requested changes
See my comments.

2022-03-13 19:01 UTC, JunxiHe459 commented on user/views.py
> +            return HttpResponse(json.dumps(response), content_type="application/json", status=404)
Status code 404 is for page not found, you should use 400 here.

2022-03-13 19:01 UTC, JunxiHe459 commented on user/views.py
> +                    response['token'] = util.jwt_auth.generate_token(payload={"username": user_info.username,
You don't have to generate a JWT here, we only give token when a user logs in.

2022-03-15 21:50 UTC, JunxiHe459 approved these changes

2022-03-15 21:52 UTC, kristeny233 approved these changes

2022-03-15 21:53 UTC, merged